{
  "kind": "Listing",
  "data": {
    "modhash": "",
    "whitelist_status": "all_ads",
    "children": [
      {
        "kind": "t3",
        "data": {
          "selftext_html": "Deine Mutter",
          "likes": null,
          "suggested_sort": "new",
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "link_flair_text": null,
          "id": "7nnjzh",
          "banned_at_utc": null,
          "mod_reason_title": null,
          "view_count": null,
          "archived": false,
          "clicked": false,
          "media_embed": {},
          "report_reasons": null,
          "author": "acemarke",
          "num_crossposts": 0,
          "saved": false,
          "mod_reports": [],
          "can_mod_post": false,
          "is_crosspostable": false,
          "pinned": false,
          "score": 8,
          "approved_by": null,
          "over_18": false,
          "hidden": false,
          "thumbnail": "self",
          "edited": false,
          "link_flair_css_class": null,
          "author_flair_css_class": null,
          "contest_mode": false,
          "gilded": 0,
          "downs": 0,
          "brand_safe": true,
          "secure_media_embed": {},
          "removal_reason": null,
          "author_flair_text": null,
          "stickied": true,
          "can_gild": false,
          "thumbnail_height": null,
          "parent_whitelist_status": "all_ads",
          "name": "t3_7nnjzh",
          "spoiler": false,
          "permalink": "/r/reactjs/comments/7nnjzh/beginners_thread_easy_questions_january_2018/",
          "subreddit_type": "public",
          "locked": false,
          "hide_score": false,
          "created": 1514940260,
          "url": "https://www.reddit.com/r/reactjs/comments/7nnjzh/beginners_thread_easy_questions_january_2018/",
          "whitelist_status": "all_ads",
          "quarantine": false,
          "title": "Beginner's Thread / Easy Questions (January 2018)",
          "created_utc": 1514911460,
          "subreddit_name_prefixed": "r/reactjs",
          "ups": 8,
          "media": null,
          "num_comments": 25,
          "is_self": true,
          "visited": false,
          "mod_note": null,
          "is_video": false,
          "distinguished": null
        }
      }
    ],
    "after": "t3_7nvs2k",
    "before": null
  }
}
